name: Copy Trivy DBs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  copy-trivy-db:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    env:
      REGISTRY: ghcr.io

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Repsitory name must be lowercase
      - name: lowercase GITHUB_REPOSITORY_OWNER
        run: |
          echo "GHCR_ORG=${GITHUB_REPOSITORY_OWNER@L}" >> ${GITHUB_ENV}

      - name: Copy the databases
        run: |
          oras cp ${{ env.REGISTRY }}/aquasecurity/trivy-db:2 ${{ env.REGISTRY }}/${{ env.GHCR_ORG }}/trivy-db-mirror:2
          oras cp ${{ env.REGISTRY }}/aquasecurity/trivy-java-db:1 ${{ env.REGISTRY }}/${{ env.GHCR_ORG }}/trivy-java-db-mirror:1
